component: website
name: duxravvel-web
app: duxravel
inputs:
  src:
    src: ./src
    hook: yarn build
    dist: ./build
    error: 404.html
  bucketName: duxphp
  protocol: https
  hosts:
     - host: www.duxravel.com
       https:
         switch: on
         http2: off
         certInfo:
           certId: 'sW9iyZUc'